### ISSUE TITLE
安装后再执行start或dev都报错，安装的依赖有问题吗？node12

### ISSUE THREAD

**Issue by wmzher** [wxbing1207/sc_admin#1]
安装后再运行start或dev都报错，安装的依赖有问题吗？

**Comment by wmzher** [comment]
![image](https://user-images.githubusercontent.com/42892253/73725604-b3fb8e80-4768-11ea-8e52-857cae518bb1.png)

**Comment by bing127** [comment]
1、下载npm-check-updates
2、ncu 更新依赖
3、启动

若还是不行，你再问

**Comment by family2hu** [comment]
我也报这个错了。
在plugin.js中，把oss的enable改成false 即可
